// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6axudAUwdZcLHh6oG3pQUqIp1AmxdmAw',
    appId: '1:1080662988948:web:7187bb3ec405065443fc81',
    messagingSenderId: '1080662988948',
    projectId: 'bloggzzi',
    authDomain: 'bloggzzi.firebaseapp.com',
    storageBucket: 'bloggzzi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZn5vQKNd_zBoYyEkrGZhrzII0ABbvqK0',
    appId: '1:1080662988948:android:571686ca860f0cf443fc81',
    messagingSenderId: '1080662988948',
    projectId: 'bloggzzi',
    storageBucket: 'bloggzzi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQmwjEUpu2NSEMc1aFx0L0v_yDJkKYA8',
    appId: '1:1080662988948:ios:59a71dde30ffb96d43fc81',
    messagingSenderId: '1080662988948',
    projectId: 'bloggzzi',
    storageBucket: 'bloggzzi.appspot.com',
    androidClientId: '1080662988948-0mimofduf4j0daa7tspjoktvb9ee5se1.apps.googleusercontent.com',
    iosClientId: '1080662988948-4o45drc3di7srn03vvsoq2s7sbk37mt2.apps.googleusercontent.com',
    iosBundleId: 'com.blogappz3.erkam.blog',
  );
}
